spring.datasource.url=jdbc:mysql://root:eYhCrLMyRrhtNVlVgTJgILrqnGLqIoos@crossover.proxy.rlwy.net:53135/railway
spring.datasource.username=root
spring.datasource.password=crossover.proxy.rlwy.net:53135/railway

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=${PORT:8080}
